AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16 # Dependent of computacional power
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2 # Health and Disease class
WEIGHTS: imagenet
LEARNING_RATE: 0.01